name: CMake
on: [push, pull_request]
jobs:
  ci-cmake:
    name: ${{ matrix.name }}
    runs-on: Windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v6

    - name: Generate project files
      run: cmake -S . -B ../build

    - name: Compile source code
      run: cmake --build ../build --config Release

    - name: Run test cases
      run: ctest -C Release --output-on-failure --max-width 120
      working-directory: ../build
